### ISSUE TITLE
Missing visualizers

### ISSUE THREAD

**Issue by damevi** [btholt/complete-intro-to-computer-science#26]
In the Frontend Masters course sort and trees visualizers are shown however in the current [CodeSandbox](https://codesandbox.io/s/upbeat-leftpad-8kdjr?fontsize=14&hidenavigation=1&theme=dark) there are no such files anymore and e.g. `Sort.js` only returns "Hi"

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/57729449/128811864-4c438bc6-cef1-4c66-8681-0a3b6bd3ce4c.png">

**Comment by lengebre** [comment]
> In the Frontend Masters course sort and trees visualizers are shown however in the current [CodeSandbox](https://codesandbox.io/s/upbeat-leftpad-8kdjr?fontsize=14&hidenavigation=1&theme=dark) there are no such files anymore and e.g. `Sort.js` only returns "Hi"
> 
> <img alt="image" width="1286" src="https://user-images.githubusercontent.com/57729449/128811864-4c438bc6-cef1-4c66-8681-0a3b6bd3ce4c.png">

Select "algorithm-exercises" to use the template. It's right under his picture

**Comment by damevi** [comment]
Thank you my man, got it!
